### ISSUE TITLE
watch command?

### ISSUE THREAD

**Issue by fasiha** [yeahoffline/redis-mock#116]
Redis docs on [transactions](https://redis.io/topics/transactions) mention a [WATCH](https://redis.io/commands/watch) command, but it isn't available in this package? Is this command not used in Node.js?

**Comment by fasiha** [comment]
Sorry, I posted this to redis-mock, and not the redis package itself, a thousand apologies. I'll post there first, and come back here if warranted.

**Comment by yeahoffline** [comment]
all good. have a nice day

**Comment by fasiha** [comment]
Am I right in seeing that redis-mock doesn't support `watch`? Any thoughts on how to add this?

**Comment by yeahoffline** [comment]
Feel free or :-)

Ahmed Fasih <notifications@github.com> schrieb am Fr., 14. Juni 2019, 01:53:

**Comment by iBlueDust** [comment]
Am I wrong in saying that the [`redis`](https://github.com/NodeRedis/node-redis#optimistic-locks) package supports `watch()` and `unwatch()` now? They would be really nice for unit testing, even as duds.
