### ISSUE TITLE
[SET] - Invalid set is returning success

### ISSUE THREAD

**Issue by andrewfreitas** [yeahoffline/redis-mock#129]
Sendind a set command with invalid keys or invalid values are returning success. It need to return an error.

For example, a set command passing a null key is returning success.

**Comment by kamiljano** [comment]
looks like there even was a test to make sure that we do just that... validated with the `redis` module and confirmed that this is not the wanted behaviour. This should be fixed, along with a bunch of other closely related things over here: https://github.com/yeahoffline/redis-mock/pull/149
