### ISSUE TITLE
Support for multiple redis instances by redis host name and port

### ISSUE THREAD

**Issue by jgresham** [yeahoffline/redis-mock#133]
Mocking multiple redis hosts by specifying a different port or host name currently doesn't work. Being able to add entries to one redis instance and keep those entries separate from another redis instance is needed for testing multiple redis client functions.
Example:
```
let client1 = redis.createClient(6379, 'redis-server-1')
let client2 = redis.createClient(6379, 'redis-server-2')
```

**Comment by yeahoffline** [comment]
feel free to submit a pr
