### ISSUE TITLE
Example for multiple databases

### ISSUE THREAD

**Issue by one000mph** [yeahoffline/redis-mock#134]
I have two different databases `0` and `1`. I see some commits that this should now be supported but I don't see any documentation or examples so I'm having trouble figuring out how to use this library feature. Any help appreciated

**Comment by one000mph** [comment]
My test calls `createClient` twice but both appear to point to the same data.

```
const redis_0 = Redis.createClient({ db: 0 });
const redis_1 = Redis.createClient({ db: 1 });
```

**Comment by one000mph** [comment]
after some fiddling I found that `redis.select(<db_int>) `does the job but this is not great for mimicking the prod `redis` library since `selects` do not normally appear in my code. I am having to add checks for `if (process.env.NODE_ENV === "test")` which I would rather not do. Is it possible to create multiple clients that point to the specified db?

**Comment by kamiljano** [comment]
You're absolutely right. The whole purpose of mock is to make it work the same way the real client would.
This is a pretty old and messy code base. I just spent 3 weeks cleaning it up only to make the fix of this problem possible.
I guess nobody before me felt like cleaning it up and this is why this ticket hasn't been addressed for such a long time.
This PR should take care of it: https://github.com/yeahoffline/redis-mock/pull/168
Now the db can be passed either through the db parameter in createClient or even mentioned as a query parameter in the URL, if you prefer using the connection string in your `createClient()` instead
