### ISSUE TITLE
cacheClient.multi(...).setex(...).renamenx is not a function

### ISSUE THREAD

**Issue by richard77** [yeahoffline/redis-mock#143]
Hi, 

I have the following setup for a rate limiter.

```
cacheClient.multi()
    .setex(tempKey, Duration.fromObject(constraint).seconds, 0)
    .renamenx(tempKey, realKey)
    .incr(realKey)
    .ttl(realKey)
    .exec(callback);
```

node:  v12.16.3
redis-mock: 0.52.0

when i call this the renamenx function call is not found. Commenting out that line works fine (albeit not functional :D)

Thanks in advance!
/Richard

Edit: removed the remark that callback was not called.. with debugging it showed it actually did. Creating a test case to verify the renamenx not being supported by multi()

**Comment by richard77** [comment]
```
 it("should have get and set, etc", function () {
    var multi = r.multi();
    should.exist(multi.get);
    should.exist(multi.set);
    should.exist(multi.GET);
    should.exist(multi.SET);
    should.exist(multi.DECR);
    should.exist(multi.decrby);
    should.exist(multi.exists);
    should.exist(multi.hget);
    should.exist(multi.exec_atomic);

    should.exist(multi.setex);
    should.exist(multi.ttl);
    should.exist(multi.incr);
    should.exist(multi.renamenx);
  });
```
this test fails on the renamenx call.

**Comment by richard77** [comment]
Ok i have a fix, want to create a PR, but cannot push to a bugfix branch. 
How do you want me to provide you with the PR?

**Comment by yeahoffline** [comment]
PRs are open, feel free to do one :)

**Comment by richard77** [comment]
Pr has been created.
