### ISSUE TITLE
Running Sorted Set operations in a Multi don't execute in order

### ISSUE THREAD

**Issue by noahsilas** [yeahoffline/redis-mock#24]
When running operations on a sorted set, I want to run a multi that:
- removes low scored items from the set (ZREMRANGEBYSCORE)
- adds an item to the set if it is not already present (ZADD NX)

If the ZREMRANGEBYSCORE Removes an element, I would expect that the ZADD NX would be able to add it back to the set, but this doesn't seem to be the behavior.

I haven't dug in to the root cause yet, but here's a test case showing the failure.
https://github.com/noahsilas/redis-mock/commit/735d5a458d78e534e0203fdfb06c097c617f9945

**Comment by yeahoffline** [comment]
fixed ?
