### ISSUE TITLE
lrem method not implemented

### ISSUE THREAD

**Issue by iVahan** [yeahoffline/redis-mock#41]
In my case I need to use lrem but there is no lrem method in redis-mock

**Comment by yeahoffline** [comment]
feel free to submit a PR :neckbeard:

**Comment by cloderic** [comment]
I'd like to reopen that, I might consider submitting a PR, is there a particular guideline on doing that ?

**Comment by yeahoffline** [comment]
nope just submit a pr and we go from there.

**Comment by cloderic** [comment]
@yeahoffline Done in #94
