### ISSUE TITLE
Difference between redis and redis-mock

### ISSUE THREAD

**Issue by jamen** [yeahoffline/redis-mock#56]
Copying `redis`'s recommended way to add a promise API:

```js
var redis = require('redis');
bluebird.promisifyAll(redis.RedisClient.prototype);
bluebird.promisifyAll(redis.Multi.prototype);
```

Like this:

```js
const redis = require('redis-mock')
const { promisifyAll } = require('bluebird')

promisifyAll(redis.RedisClient.prototype)
```

Creates a situation that doesn't work with `redis-mock`:

1. `client.set(token, userid)`
2. `client.exists(token)`

**Comment by jamen** [comment]
Decided that `redis-server` + `redis` was sufficient alternative.  :)

**Comment by dyong0** [comment]
@jamen I had the same issue. Do you mean you ran tests with an actual redis?

**Comment by jamen** [comment]
@dyong0 Yeah.  Using `redis-server` to create a fresh one for testing, and connecting to it with the normal `redis` library.  Found this to be the most compatible method as opposed to using mock libraries.
