### ISSUE TITLE
Repo maintainer is not available

### ISSUE THREAD

**Issue by animir** [yeahoffline/redis-mock#72]
Repo maintainer is not available for several months.
There are several useful PRs, but CI for them fails with the same errors randomly:
1. `publish and subscribe should only receive message on channels psubscribed to:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.`
2. `"after each" hook:
     Uncaught AbortError: Ready check failed: Stream connection ended and command aborted. It might have been processed.`

These errors are not related to any errors and they are random, so looks like it is a problem with tests.

However, we still need fixes and new features.
I suggest to create new PRs to this repo https://github.com/animir/redis-mock
I'll manually check build errors and merge PR if errors are not related to changes.
I'll merge my repo back to this repo, when maintainer is back online.

Also, please, look into those errors, may be someone will get luck to fix them.
I've tried some hacks here https://github.com/animir/redis-mock/commit/59bb7903cfe5883fc185ee2dac0104fd4ddfcf35, but it fixed only 1 error

Thanks.

**Comment by yeahoffline** [comment]
i am available. feel free to submit a pr with working tests

**Comment by yeahoffline** [comment]
or take over the repo

**Comment by animir** [comment]
@yeahoffline Nice to see you!
There are some random test errors during builds, which don't look like something critical.
Nobody have not fixed them yet.
However, there are many PRs which are useful and can be merged.
I've already merged them in my repo I mentioned and started using in my project.
I'm free to switch back to this repo, when PRs are merged
I can help with this repo time to time

**Comment by yeahoffline** [comment]
i see... 

merged those prs.

working tests would be great, its a great indicator
