### ISSUE TITLE
Use of arrays as command arguments

### ISSUE THREAD

**Issue by mapolonio** [yeahoffline/redis-mock#83]
In the node_redis official documentation they state that arrays can be used along with individual arguments (see https://github.com/NodeRedis/node_redis#sending-commands). But in redis-mock the behaviour is not the same:

(I have promisified the client)
```
const client = redis.createClient();

await client.saddAsync('mySet', ['a', 'b', 'c']);

const members = await client.smembersAsync('mySet');

console.log(members);
// In node_redis: ['a', 'b', 'c'] (3 members)
// In redis-mock: '["a", "b", "c"]' (1 member, the array stringified)
```

**Comment by hugoduraes** [comment]
Just stumbled upon this issue. Can it be fixed?

**Comment by mapolonio** [comment]
I ended up doing something like this

```
const originalMethod = client.saddAsync;

client.saddAsync = function(...args) {
      return originalMethod(..._.flatten(args));
};
```

**Comment by hugoduraes** [comment]
@mapolonio which methods have you found that don't accept array as arguments?

**Comment by hugoduraes** [comment]
@yeahoffline I've just created a PR to fix this issue. Can you have a look at it? Thanks.
