### ISSUE TITLE
All functions return undefined and doesn't set value

### ISSUE THREAD

**Issue by mauricioklein** [yeahoffline/redis-mock#89]
I'm trying to use `redis-mock` but no call is being accepted. All of them returns undefined and the callback isn't called.

```js
const mock = require("redis-mock")
const client = mock.createClient()

client.SET("x", "5", ()=>{})
// undefined

client.GET("x", (err, val) => console.log(err, val))
// undefined, and nothing is printed
```

This happens to all redis supported functions.

Any hint about what the problem could be?

Thanks!

**Comment by yeahoffline** [comment]
your first line does not log anything?
the second line does return an undefined error and  '5' for val actually
