### ISSUE TITLE
Multi: TypeError: operations.decr is not a function

### ISSUE THREAD

**Issue by rjnienaber** [yeahoffline/redis-mock#99]
I was trying to use the `multi` command today and I kept getting this error:

```
TypeError: operations.decr is not a function
```

Looking into the code, [this list](https://github.com/yeahoffline/redis-mock/blob/49b7972a72eda93b8cc6b3e37e3b188ff1ff3bcf/lib/multi.js#L131) appears to be incomplete. Would it be as simple as adding it to this list?

As a workaround, I used `.incrby(<key>, -1)`.

**Comment by yeahoffline** [comment]
feel free to submit a pr
